mappings:
  DirectCreditPayment_ViaCheque: Sunnysideup\PaymentDirectcredit\DirectCreditPaymentViaCheque
  DirectCreditPayment_TESTSUCCESS: Sunnysideup\PaymentDirectcredit\DirectCreditPaymentTESTSUCCESS
  DirectCreditPayment_ViaCreditCart: Sunnysideup\PaymentDirectcredit\DirectCreditPaymentViaCreditCart
  DirectCreditPayment_TESTFAILURE: Sunnysideup\PaymentDirectcredit\DirectCreditPaymentTESTFAILURE
  DirectCreditPayment: Sunnysideup\PaymentDirectcredit\DirectCreditPayment
